import { Metadata } from 'next'

import '../styles/globals.css'

import Home from '~/organisms/Home/pages'
export const metadata: Metadata = {
  title: 'discover',
  description: 'Generated by create next app',
}

const RootPage = () => {
  return (
    <>
      <Home />
    </>
  )
}

export default RootPage
