import { Metadata } from 'next'

import Home from '@/app/components/organisms/Home/pages'
import App from '@/pages/_app'

import Navigation from './components/common/Navigation/page'

export const metadata: Metadata = {
  title: 'discover',
  description: 'Generated by create next app',
}

const Page = () => {
  return (
    <>
      <Navigation />
      <App Component={Home} />
    </>
  )
}

export default Page
