import { Metadata } from 'next'

import '../styles/globals.css'

import Footer from '~/common/Footer/page'
import Header from '~/common/Header/page'
import Home from '~/organisms/Home/pages'
export const metadata: Metadata = {
  title: 'discover',
  description: 'Generated by create next app',
}

const RootPage = () => {
  return (
    <>
      <Header />
      <Home />
      <Footer />
    </>
  )
}

export default RootPage
